# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  description: "Rust TOML Parser"
  homepage: "https://docs.rs/toml"
  topics: "rust toml"
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: main

  # Preference: people do clean commits
  allow_merge_commit: true
  # Backup in case we need to clean up commits
  allow_squash_merge: true
  # Not really needed
  allow_rebase_merge: false

  allow_auto_merge: true
  delete_branch_on_merge: true

  squash_merge_commit_title: "PR_TITLE"
  squash_merge_commit_message: "PR_BODY"
  merge_commit_message: "PR_BODY"

labels:
  - name: "A-parse"
    description: "Area: Parsing TOML"
    color: '#f7e101'
  - name: "A-edit"
    description: "Area: TOML editing API"
    color: '#f7e101'
  - name: "A-output"
    description: "Area: Outputting TOML"
    color: '#f7e101'
  - name: "A-serde"
    description: "Area: Serde integration"
    color: '#f7e101'
  - name: "A-error"
    description: "Area: Error reporting"
    color: '#f7e101'
  - name: "A-docs"
    description: "Area: Documentation"
    color: '#f7e101'
  - name: "A-meta"
    description: "Area: Project-wide"
    color: '#f7e101'
  - name: "C-bug"
    description: "Category: Things not working as expected"
    color: '#f5f1fd'
  - name: "C-enhancement"
    description: "Category: Raise on the bar on expectations"
    color: '#f5f1fd'
  - name: "C-question"
    description: Uncertainty is involved
    color: '#f5f1fd'
  - name: "M-breaking-change"
    description: "Meta: Implementing or merging this will introduce a breaking change."
    color: '#E10C02'
  - name: "E-help-wanted"
    description: "Call for participation: Help is requested to fix this issue."
    color: '#02E10C'

branches:
  - name: main
    protection:
      required_pull_request_reviews: null
      required_conversation_resolution: true
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: false
        contexts: ["CI", "Lint Commits", "Spell Check with Typos"]
      enforce_admins: false
      restrictions: null
